[pytest]
log_cli = true
log_cli_level = WARNING
log_cli_format = %(message)s
filterwarnings =
    ignore:.*Please use `import python_multipart` instead.*:PendingDeprecationWarning
    ignore::PendingDeprecationWarning:starlette.formparsers

