name: CI - Atlas Project Tests

on:
  push:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env.dev file from secret
        run: |
          echo "${{ secrets.ENV_DEV }}" > ./Backend-Atlas/.env.dev

      - name: Set up Docker Compose
        run: |
          docker compose version

      - name: Build all services
        run: docker compose build

      - name: Run fast unit tests in parallel
        run: >
          docker compose run --rm -q test-backend
          pytest tests/ -n auto -v --color=yes --tb=short -rA
          -m "not integration and not slow"

      - name: Run OCR integration tests sequentially
        run: >
          docker compose run --rm -q test-backend
          pytest tests/ -v --color=yes --tb=short -rA -o log_cli=true --log-cli-level=INFO
          -m "integration"
